env:
  global:
    - CC_TEST_REPORTER_ID=66e5c9ee0b4d67ac62195fc0b16cd29bb5169d810f33b817bbcfc3e398871aaa
dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
  - openjdk10
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
